### ISSUE TITLE
vue 本地json文件不能生产动画 一直报错

### ISSUE THREAD

**Issue by yuanb7263050** [galacean/effects-vue-demo#1]
使用的给的demo，实例在线json是可以的。但是我自己
![1733123783431](https://github.com/user-attachments/assets/e639ee2f-1d14-443b-8113-935309b8da17)
![1733123791749](https://github.com/user-attachments/assets/8fe97f7d-05dc-4a74-9382-0c656342509e)
本地的不行， 一直报错，修改了图片路径也不行,麻烦帮忙看一下

**Comment by yuanb7263050** [comment]
{"playerVersion":{"web":"2.1.0","native":"0.0.1.202311221223"},"images":[{"url":"./images/adf1ea9dfa33eb3f4d3d151b0e7eccdd.png","id":"98c98d6c32c240a0b99945c19050e858","renderLevel":"B+","avif":"blob:https://galacean.antgroup.com/98468dad-5b33-4252-be24-cfed00ff231e","webp":"./images/9a57f38be86e16d3011991effd68347b.webp"},{"url":"./images/6234435fad6786ea289cf5dfa82f2d53.png","id":"8fa91f9dc8ac4637856ea415b1da1c6b","renderLevel":"B+","avif":"blob:https://galacean.antgroup.com/0c3f04d0-99c8-4024-ae32-b82738b69de2","webp":"./images/07bbfcbe02dbe8d74d7ffa9d2a2efb16.webp"},{"url":"./images/0442de1e479ca56ef7b408b595b41295.png","id":"c2266327b8534e90bd0c459807f8229d","renderLevel":"B+","avif":"blob:https://galacean.antgroup.com/b435757a-5245-415d-a2e2-c45d2a02c576","webp":"./images/b16b5badc9d8c023d2f02ef79c4df392.webp"},{"url":"./images/fea3fc67fc1a09d58344bdde56d26f40.png","id":"8da0736f88954e66952a65859a4cea38","renderLevel":"B+","avif":"blob:https://galacean.antgroup.com/dc95519b-8c9d-4e05-be5d-8dc485d3cae6","webp":"./images/49f3d6ae5c8718a5d182985a1e5b5a57.webp"}],"fonts":[],"version":"3.1","shapes":[],"plugins":[],"type":"ge","compositions":[{"id":"1","name":"3","duration":5,"startTime":0,"endBehavior":2,"previewSize":[1080,1920],"items":

**Comment by yiiqii** [comment]
编译用的 vite？

**Comment by yuanb7263050** [comment]
是的

**Comment by yiiqii** [comment]
vite 的话请把资源放在 public 目录下，这是基础哦：https://cn.vite.dev/guide/assets.html#the-public-directory

**Comment by yuanb7263050** [comment]
![1733124326660](https://github.com/user-attachments/assets/3460509c-7cf0-45aa-8d6d-9093cbcafd00)

**Comment by yuanb7263050** [comment]
已经放到public 但是报一样的错误

**Comment by yuanb7263050** [comment]
![1733124487527](https://github.com/user-attachments/assets/3ca2d23c-8369-4687-ac1b-4bf10f642b10)

**Comment by yuanb7263050** [comment]
[Uploading 闭眼.zip…]()

**Comment by yuanb7263050** [comment]
这是导出时的选项，麻烦你了

**Comment by yuanb7263050** [comment]
![1733124790193](https://github.com/user-attachments/assets/fbe0556c-264c-4146-858d-d38da04916eb)

**Comment by yuanb7263050** [comment]
[闭眼.zip](https://github.com/user-attachments/files/17974256/default.zip)

**Comment by yuanb7263050** [comment]
我不知道问题出在哪儿，是导出有问题还是什么原因，文件路径按照要求放在了public里面了，但是还是报错，这个问题在其他地方也获取不到帮助，请问有讨论群或者类似的地方吗？麻烦了

**Comment by yiiqii** [comment]
<img width="458" alt="image" src="https://github.com/user-attachments/assets/27386c3b-3085-4ccf-a3cb-ebc324401b62">
需要升级 runtime 版本到最新的 2.1.2，因为导出的是最新的产物，产物和 runtime 是版本关联的：https://www.galacean.com/effects/user/inxl16girkdl5gbg

**Comment by yiiqii** [comment]
这个 demo 我们会更新一下版本

**Comment by yuanb7263050** [comment]
好的，大概什么时候更新版本，想请教一下，如果适配uniapp 哪个版本最合适，谢谢你了

**Comment by yiiqii** [comment]
uniapp 小程序没有做适配，需要你自己尝试了，你可以直接更新 demo 中的 dependencies，如上截图

**Comment by yiiqii** [comment]
![image](https://github.com/user-attachments/assets/e5b52501-a632-4296-b4e7-8ba51ff53e89)
官网首页底部有答疑交流群

**Comment by yuanb7263050** [comment]
好的，谢谢解答，非常感谢
